# Site settings
title: Nihar Gupte
description: B.S. in Computer Science
baseurl: "" # the subpath of your site, e.g. /blog
url: "nihargupte.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nihar Gupte
user_description: I am a senior year undergraduate student at The University of Texas at Arlington pursuing my Bachelors in Computer Science with a certificate in Cyber Security and minor in Mathematics. I have a strong technical background with expertise in Java, JavaScript and C programming and numerous academic projects to demonstrate the same. I have an immense passion for learning new technologies with a truly high ambition of making positive and noteworthy contributions in the field of Software Development, Full Stack Web Development, and Information Security / Cyber Security fields.
user_description2: I am currently working as a DevOps/SecOps Analyst with the Office of Information Technology at The University of Texas at Arlington, having worked on the SIEM tool of Azure Sentinel and on the analytical visualizing tool of Grafana.
user_description3: With a broad skill set covering important facets in the technology field, I am looking for exciting new grad opportunities, beginning May 2021 to put my skills to real-world use in the industry and gain more practical experience. 
user_title: B.S. in Computer Science
user_title2: University of Texas at Arlington, May 2021

email: nihargupte2008@gmail.com
twitter_username: iamNihar07
github_username:  iamNihar07
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
