# Site settings
title: Nihar Gupte
description: Software Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "iamnihar07.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nihar Gupte
user_description: I am currently working as a Software Developer on the FIRST Team for the AT&T Division of Amdocs Inc. I graduated with a major in Computer Science and a minor in Mathematics along with a certificate in Cyber Security from the University of Texas at Arlington with Summa Cum Laude Latin Honors in May 2021. I have previously also worked as a DevOps/SecOps Analyst with the Office of Information Technology at The University of Texas at Arlington where I worked on the SIEM tool of Azure Sentinel and on the analytical visualizing tool of Grafana.
user_description3: I can be reached via email at nihargupte2008@gmail.com.
user_description2: With a broad skill set covering important facets in the technology field, I have a strong technical background with expertise in Java, JavaScript and C programming and numerous academic projects to demonstrate the same. I have an immense passion for learning new technologies with a truly high ambition of making positive and noteworthy contributions in the field of Software Development, Full Stack Web Development, and Information Security / Cyber Security fields.
user_title: Software Developer @ Amdocs Inc.
user_title2: B.S. in Computer Science, University of Texas at Arlington, May 2021

email: nihargupte2008@gmail.com
twitter_username: iamNihar07
github_username:  iamNihar07
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']